# -*- coding: utf-8 -*-
"""Stock-Data-Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ovitorsena/financial-analysis/blob/main/Stock_Data_Analysis.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime 
from pandas.plotting import scatter_matrix
import yfinance as yf
# %matplotlib inline

start = pd.to_datetime('2021-01-01')
end = pd.to_datetime('2022-01-01')

"""##The analysis of Shopify and Amazon were intentionally separated to understand the metrics of each individually and compare them to the other general stocks.

##Getting data from stock exchange
"""

#NYSE = yf.download ('SHOP WMT TGT CHWY JMIA', start,end) 
#NASDAQ = yf.download ('AMZN ETSY EBAY OSTK WISH', start,end)

#NYSE
SHOP = yf.download ('SHOP', start,end)
WMT = yf.download ('WMT', start,end)
TGT = yf.download ('TGT', start,end)
CHWY = yf.download ('CHWY', start,end)
JMIA = yf.download ('JMIA', start,end)

#NASDAQ
AMZN = yf.download ('AMZN', start,end)
ETSY = yf.download ('ETSY', start,end)
EBAY = yf.download ('EBAY', start,end)
OSTK = yf.download ('OSTK', start,end)
WISH = yf.download ('WISH', start,end)

"""###Stock NYSE - 12-month stock opening price


"""

WMT['Open'].plot(label = 'WMT', figsize = (20,7))
TGT['Open'].plot(label = 'TGT')
CHWY['Open'].plot(label = 'CHWY')
JMIA['Open'].plot(label = 'JMIA')
plt.title('Stock Open Prices of NYSE : SHOP / WMT / TGT / CHMW / JMIA')
plt.legend()

SHOP['Open'].plot(label = 'SHOP', figsize = (20,7))
plt.title('Stock Open Prices of NYSE : SHOP')
plt.legend()

"""###Stock NYSE - 12-month stock high price


"""

WMT['High'].plot(label = 'WMT', figsize = (20,7))
TGT['High'].plot(label = 'TGT')
CHWY['High'].plot(label = 'CHWY')
JMIA['High'].plot(label = 'JMIA')
plt.title('Stock High Prices of NYSE :WMT / TGT / CHMW / JMIA')
plt.legend()

SHOP['High'].plot(label = 'SHOP', figsize = (15,7))
plt.title('Stock High Prices of NYSE : SHOP')
plt.legend()

"""###Stock NYSE - 12-month stock low price


"""

WMT['Low'].plot(label = 'WMT', figsize = (15,7))
TGT['Low'].plot(label = 'TGT')
CHWY['Low'].plot(label = 'CHWY')
JMIA['Low'].plot(label = 'JMIA')
plt.title('Stock Low Prices of NYSE : WMT / TGT / CHMW / JMIA')
plt.legend()

SHOP['Low'].plot(label = 'SHOP', figsize = (15,7))
plt.title('Stock Low Prices of NYSE : SHOP ')
plt.legend()

"""###Stock closing price in 12 months"""

WMT['Close'].plot(label = 'WMT', figsize = (20,7))
TGT['Close'].plot(label = 'TGT')
CHWY['Close'].plot(label = 'CHWY')
JMIA['Close'].plot(label = 'JMIA')
plt.title('Stock Close Prices of NYSE : WMT / TGT / CHMW / JMIA')
plt.legend()

SHOP['Close'].plot(label = 'SHOP', figsize = (20,7))
plt.title('Stock Close Prices of NYSE : SHOP')
plt.legend()

"""###Traded volume of the stock in 12 months"""

SHOP['Volume'].plot(label = 'SHOP', figsize =(20,7))
WMT['Volume'].plot(label = 'WMT')
TGT['Volume'].plot(label = 'TGT')
CHWY['Volume'].plot(label = 'CHWY')
JMIA['Volume'].plot(label = 'JMIA')
plt.title('Volume of Stock Traded in NYSE')
plt.legend()

"""###Stock NYSE - 12-month marketcap"""

SHOP['MarktCap'] = SHOP['Open'] * SHOP['Volume']
WMT['MarktCap'] = WMT['Open'] * WMT['Volume']
TGT['MarktCap'] = TGT['Open'] * TGT['Volume']
CHWY['MarktCap'] = CHWY['Open'] * CHWY['Volume']
JMIA['MarktCap'] = JMIA['Open'] * JMIA['Volume']

SHOP['MarktCap'].plot(label = 'SHOP', figsize =(20,7))
WMT['MarktCap'].plot(label = 'WMT')
TGT['MarktCap'].plot(label = 'TGT')
CHWY['MarktCap'].plot(label = 'CHWY')
JMIA['MarktCap'].plot(label = 'JMIA')
plt.title('Market Cap - NYSE')
plt.legend()

"""###Stock NYSE - 50 to 200-day trend patterns"""

#TRENDS
SHOP['MA50'] = SHOP['Open'].rolling(50).mean()
SHOP['MA200'] = SHOP['Open'].rolling(200).mean()

WMT['MA50'] = WMT['Open'].rolling(50).mean()
WMT['MA200'] = WMT['Open'].rolling(200).mean()

TGT['MA50'] = TGT['Open'].rolling(50).mean()
TGT['MA200'] = TGT['Open'].rolling(200).mean()

CHWY['MA50'] = CHWY['Open'].rolling(50).mean()
CHWY['MA200'] = CHWY['Open'].rolling(200).mean()

JMIA['MA50'] = JMIA['Open'].rolling(50).mean()
JMIA['MA200'] = JMIA['Open'].rolling(200).mean()

SHOP['Open'].plot(figsize = (15,7))
SHOP['MA50'].plot()
SHOP['MA200'].plot()
plt.title('Stock NYSE Price Trend - SHOP')
plt.legend()

WMT['Open'].plot(figsize = (15,7))
WMT['MA50'].plot()
WMT['MA200'].plot()
plt.title('Stock NYSE Price Trend - WMT')
plt.legend()

TGT['Open'].plot(figsize = (15,7))
TGT['MA50'].plot()
TGT['MA200'].plot()
plt.title('Stock NYSE Price Trend - TGT')
plt.legend()

CHWY['Open'].plot(figsize = (15,7))
CHWY['MA50'].plot()
CHWY['MA200'].plot()
plt.title('Stock NYSE Price Trend - CHWY')
plt.legend()

JMIA['Open'].plot(figsize = (15,7))
JMIA['MA50'].plot()
JMIA['MA200'].plot()
plt.title('Stock NYSE Price Trend - JMIA')
plt.legend()

"""###Volatility trends"""

SHOP['returns'] = (SHOP['Close']/SHOP['Close'].shift(1)) - 1
WMT['returns'] = (WMT['Close']/WMT['Close'].shift(1))-1
TGT['returns'] = (TGT['Close']/TGT['Close'].shift(1))-1
CHWY['returns'] = (CHWY['Close']/CHWY['Close'].shift(1))-1
JMIA['returns'] = (JMIA['Close']/JMIA['Close'].shift(1))-1

SHOP['returns'].hist(bins = 100, label = 'SHOP', alpha = 0.5, figsize = (15,7))
WMT['returns'].hist(bins = 100, label = 'WMT', alpha = 0.5)
TGT['returns'].hist(bins = 100, label = 'TGT', alpha = 0.5)
CHWY['returns'].hist(bins = 100, label = 'CHWY', alpha = 0.5)
JMIA['returns'].hist(bins = 100, label = 'JMIA', alpha = 0.5)

plt.title('Volatility Stock - NYSE')
plt.legend()

"""#NASDAQ Stock exchange"""

WISH['Open'].plot(label = 'WISH' ,figsize = (20,7))
OSTK['Open'].plot(label = 'OSTK')
EBAY['Open'].plot(label = 'EBAY')
ETSY['Open'].plot(label = 'ETSY')
plt.title('Stock Open Prices of NYSE : ETSY /  EBAY / OSTK / WISH')
plt.legend()

AMZN['Open'].plot(label = 'AMZN', figsize = (20,7))
plt.title('Stock Open Prices of NYSE : AMZN')
plt.legend()

